### ISSUE TITLE
Add bloom filter data to erofs images

### ISSUE THREAD

**Issue by alexlarsson** [containers/composefs#167]
This patch-set adds support to erofs for bloom filters to speed up negative xattr lookups:
https://lists.ozlabs.org/pipermail/linux-erofs/2023-July/008565.html

This change is backwards compat in the sense that we could add these to the erofs images we generate and old kernels would still work with the images. It would be good to get this into our erofs image format before we formally lock down the v0 binary format.

**Comment by hsiangkao** [comment]
Cc @lostjeffle

**Comment by alexlarsson** [comment]
v3 was posted here: https://lists.ozlabs.org/pipermail/linux-erofs/2023-July/008669.html

**Comment by cgwalters** [comment]
> It would be good to get this into our erofs image format before we formally lock down the v0 binary format.

Is that the *only* thing you see blocking a v0?  

I feel like we should do some sort of group "audit" or pass-through of *exactly* what is in the EROFS images we're generating and whether it covers everything it needs to and it looks sane or so.  Did anyone already do that?

**Comment by alexlarsson** [comment]
Offhand the other thing I see is whether to keep the `00` to `ff` whiteouts, which are only needed if the new overlayfs data-only layers are unsupported.

**Comment by alexlarsson** [comment]
Well, the other thing is that I'd like to see the overlayfs fs-verity digest xattr support in a released kernel. But we're *almost* there with that.

**Comment by cgwalters** [comment]
> Offhand the other thing I see is whether to keep the 00 to ff whiteouts, which are only needed if the new overlayfs data-only layers are unsupported.

Ah yes.  Related to that Giuseppe suggested somewhere to at least short term move them to a `.cfs` subdirectory, that seems a little nicer - then we only need one whiteout.

I dunno.  Hmmm....

Will existing erofs.ko barf if we have the bloom filters now?  Or we just want to be sure it's landed upstream before committing to it?

**Comment by hsiangkao** [comment]
> Or we just want to be sure it's landed upstream before committing to it?

xattr bloom filter on-disk format is almost fixed (I have see no more problem), I think it will be landed upstream when the next merge window is open.

**Comment by alexlarsson** [comment]
Adding the xattrs is compat, we just want to wait until the erofs format changes are deemed final.

**Comment by alexlarsson** [comment]
> > Or we just want to be sure it's landed upstream before committing to it?
> 
> xattr bloom filter on-disk format [1] is almost fixed (I have see no more problem), I think it will be landed upstream when the next merge window is open.
> 
> [1] https://lore.kernel.org/r/20230714031034.53210-2-jefflexu@linux.alibaba.com

That will be the same time as the overlayfs fs-digest changes land, so i think 6.6 will be a good baseline for v0.

**Comment by cgwalters** [comment]
Hmm, tricky.  So I can definitely see people wanting to use composefs on kernels older than 6.6.  The bloom filter stuff is a back-compat change, so we can just do it now.

The whiteouts thing is harder because it absolutely shows up in the erofs instance and are hence part of the computed digest.  But we won't need them later.

Hmmm....so I know this would be a hacky thing to do, but I could imagine changing things now such that we detect the case where the running kernel doesn't do datalowers (as we do now), and in that case, we do something like:

- Create a directory in `/run/composefs/old-kernel-no-datalower-whiteouts` that has the whiteouts
- Inject this directory just above the erofs instance

I think that'd work...and it'd be an ugly duckling that would just Go Away later.
