### ISSUE TITLE
`mkcomposefs --from-file` ignores last line without newline

### ISSUE THREAD

**Issue by cgwalters** [containers/composefs#327]
It took me an unfortunate amount of time to figure out that there's a bug in `tree_from_dump()` where basically we ignore the last chunk of a dumpfile if it doesn't end in a newline.

```
$ cat dump-nonl.txt
/ 4096 40555 222 0 0 10 0.0 - - - trusted.foo1=bar-1 user.foo2=bar-2
/a 0 100644 1 0 0 0 0.0 - - -
/b 0 100644 1 0 0 0 0.0 - - -
$ open /tmp/dump-nonl.txt | base64 -w 0
LyA0MDk2IDQwNTU1IDIyMiAwIDAgMTAgMC4wIC0gLSAtIHRydXN0ZWQuZm9vMT1iYXItMSB1c2VyLmZvbzI9YmFyLTIKL2EgMCAxMDA2NDQgMSAwIDAgMCAwLjAgLSAtIC0KL2IgMCAxMDA2NDQgMSAwIDAgMCAwLjAgLSAtIC0=
$ mkcomposefs --from-file dump-nonl.txt out.cfs
$ composefs-info dump out.cfs
/ 4096 40555 2 0 0 0 0.0 - - - trusted.foo1=bar-1 user.foo2=bar-2
/a 0 100644 1 0 0 0 0.0 - - -
$
```

The question is...what do we do about it? I guess it's *probably* unlikely someone was relying on this behavior, but it's hard to say that definitively.

I guess I lean towards changing the behavior to be an error (i.e. a trailing newline is required). But I am curious if others have opinions.

**Comment by jeckersb** [comment]
I lean towards allowing the no-newline case, only because `composefs-dump(5)` says:
```
The file format is very simple, with one file per line[...]

Fields are separated by a single space, and lines by a single newline.
```
Which as-documented to me only requires them to be separated by a newline but not terminated by one.  So I think to keep the previously-published behavior it would be better to allow it.  If it's disallowed, then at the very least the docs should be updated to reflect the requirement.

**Comment by cgwalters** [comment]
OK I've updated https://github.com/containers/composefs/pull/331
